name: Tests

on:
  push:
  pull_request:

jobs:
  linux_tests:
    name: PHP ${{ matrix.php }} - ${{ matrix.stability }} - Linux
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: convertible
        ports:
          - 33306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    strategy:
      fail-fast: true
      matrix:
        php: [7.4, 8.0]
        stability: [prefer-stable]

    steps:
      - name: üßê Checkout code
        uses: actions/checkout@v2.3.3

      - name: üî• Setup PHP with pecl extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: pecl, php-cs-fixer, phpunit, composer:v2
          extensions: swoole, fileinfo, gmp, intl, json, mbstring, openssl, dom, curl, libxml, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, dom, redis, memcached
          coverage: pcov

      - name: üç≠ Use Node JS
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x

      - name: ‚õë Setup problem matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: üëçüèº Verify MySQL connection
        run: |
          mysql --version
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -e "SHOW DATABASES"

      - name: üìñ Cache composer dependencies
        uses: actions/cache@v2.1.1
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: üì¶ Install dependencies
        run: |
          php --version
          composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress
          npm install
          npm run production
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: true

      - name: üõ´ Boot application
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan --version

      - name: ü¶Ö Migrate database
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USERNAME: root
        run: |
          mysql --version
          php artisan migrate:fresh --seed

      - name: üß™ Run PHP tests
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USERNAME: root
        run: php artisan test --parallel

      - name: Execute Code Sniffer via phpcs
	      run: |
	        composer require --dev squizlabs/php_codesniffer
	        vendor/bin/phpcs --standard=PSR12 app

	    - name: Execute Code Static Analysis (PSALM)
	      run: |
	        composer require --dev vimeo/psalm
	        ./vendor/bin/psalm --init
	        composer require --dev psalm/plugin-laravel
	        ./vendor/bin/psalm-plugin enable psalm/plugin-laravel
	        vendor/bin/psalm

  windows_tests:
    name: PHP ${{ matrix.php }} - ${{ matrix.stability }} - Windows
    runs-on: windows-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.0]
        stability: [prefer-stable]

    steps:
      - name: ‚úÖ Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: üßê Checkout code
        uses: actions/checkout@v2.3.3

      - name: üî• Setup PHP with pecl extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: pecl, php-cs-fixer, phpunit, composer:v2
          extensions: swoole, fileinfo, gmp, intl, json, mbstring, openssl, dom, curl, libxml, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, dom, redis, memcached
          coverage: pcov

      - name: üç≠ Use Node JS
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x

      - name: ‚õë Setup problem matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Cache composer dependencies üìñ
        uses: actions/cache@v2.1.1
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: üì¶ Install dependencies
        run: |
          php --version
          composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress
          npm install
          npm run production
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: true

      - name: üõ´ Boot application
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan --version

      - name: üß™ Run PHP tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'
        run: php artisan test --parallel

      - name: Execute Code Sniffer via phpcs
	      run: |
	        composer require --dev squizlabs/php_codesniffer
	        vendor/bin/phpcs --standard=PSR12 app

	    - name: Execute Code Static Analysis (PSALM)
	      run: |
	        composer require --dev vimeo/psalm
	        ./vendor/bin/psalm --init
	        composer require --dev psalm/plugin-laravel
	        ./vendor/bin/psalm-plugin enable psalm/plugin-laravel
	        vendor/bin/psalm
